name: Regenerate Python Library
on:
  workflow_dispatch:
    inputs:
      library_version:
        description: 'The version of the new library'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Delete folder
        run: |
          rm -rf meraki
      - name: Regenerate Python Library
        run: |
          python generator/generate_library.py -g true -v ${{ github.event.inputs.library_version }}
      - name: Commit changes to new branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: support@meraki.com
          message: Automatically regenerated library.
          new_branch: release
